/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import config.Koneksi;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.net.URL;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.MenuElement;
import javax.swing.MenuSelectionManager;
import javax.swing.SwingUtilities;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nadhi
 */
public class MenuUtama extends javax.swing.JFrame {   
    public static Connection conn;
    public static ResultSet rs;
    private Statement st;
    int xx, xy ;
    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        //tampilTabel();
        
        initComponents();
        conn = Koneksi.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableCellEditor1 = new dynamic_subjtable.TableCellEditor();
        dateChooser1 = new com.raven.datechooser.DateChooser();
        pn_kiri = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JButton();
        btn_matakuliah = new javax.swing.JButton();
        btn_dataDosen = new javax.swing.JButton();
        btn_mahasiswa = new javax.swing.JButton();
        btn_absen = new javax.swing.JButton();
        pn_kanan = new javax.swing.JPanel();
        pn_navbar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pn_dasar = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();
        pn_mahasiswa = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMahasiswa = new dynamic_subjtable.TableCustom();
        btn_tampilDataMahasiswa = new javax.swing.JButton();
        pn_dosen = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDosen = new dynamic_subjtable.TableCustom();
        btn_tampilDataDosen = new javax.swing.JButton();
        pn_matakuliah = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblMatakuliah = new dynamic_subjtable.TableCustom();
        btn_tampilMatakuliah = new javax.swing.JButton();
        pn_absen = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lb_npm = new javax.swing.JLabel();
        t_id = new javax.swing.JTextField();
        lb_matkul = new javax.swing.JLabel();
        lb_keterangan = new javax.swing.JLabel();
        comboMK1 = new javax.swing.JComboBox<>();
        comboKet = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        t_namaMahasiswa = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        t_email = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        t_telepon = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        t_npmMahasiswa = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Absen = new dynamic_subjtable.TableCustom();
        btn_npmMahasiswa = new javax.swing.JButton();
        btn_Submit = new javax.swing.JButton();
        pn_dashboard = new javax.swing.JPanel();
        btn_rekap = new javax.swing.JButton();
        card_mahasiswa = new javax.swing.JPanel();
        lb_mahasiswa = new javax.swing.JLabel();
        lb_jumlahmhs = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        card_mahasiswa1 = new javax.swing.JPanel();
        lb_mahasiswa1 = new javax.swing.JLabel();
        lb_jumlahDsn = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        card_mahasiswa2 = new javax.swing.JPanel();
        lb_mahasiswa2 = new javax.swing.JLabel();
        lb_jumlahMk = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbl_rekap = new dynamic_subjtable.TableCustom();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        pn_kiri.setBackground(new java.awt.Color(255, 255, 255));
        pn_kiri.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SIAKAD - Kelas F");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_perguruanTinggi_1.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        btn_dashboard.setBackground(new java.awt.Color(204, 255, 255));
        btn_dashboard.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_dashboard.setForeground(new java.awt.Color(102, 102, 102));
        btn_dashboard.setText("Dashboard");
        btn_dashboard.setBorder(null);
        btn_dashboard.setBorderPainted(false);
        btn_dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_dashboard.setDefaultCapable(false);
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });

        btn_matakuliah.setBackground(new java.awt.Color(204, 255, 255));
        btn_matakuliah.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_matakuliah.setForeground(new java.awt.Color(102, 102, 102));
        btn_matakuliah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Literature.png"))); // NOI18N
        btn_matakuliah.setText("Matakuliah");
        btn_matakuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_matakuliahActionPerformed(evt);
            }
        });

        btn_dataDosen.setBackground(new java.awt.Color(204, 255, 255));
        btn_dataDosen.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_dataDosen.setForeground(new java.awt.Color(102, 102, 102));
        btn_dataDosen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Training.png"))); // NOI18N
        btn_dataDosen.setText("Data Dosen");
        btn_dataDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dataDosenActionPerformed(evt);
            }
        });

        btn_mahasiswa.setBackground(new java.awt.Color(204, 255, 255));
        btn_mahasiswa.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_mahasiswa.setForeground(new java.awt.Color(102, 102, 102));
        btn_mahasiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Student Male.png"))); // NOI18N
        btn_mahasiswa.setText("Data Mahasiswa");
        btn_mahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mahasiswaActionPerformed(evt);
            }
        });

        btn_absen.setBackground(new java.awt.Color(204, 255, 255));
        btn_absen.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_absen.setForeground(new java.awt.Color(102, 102, 102));
        btn_absen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Literature.png"))); // NOI18N
        btn_absen.setText("Absen Mahasiswa");
        btn_absen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_absenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_kiriLayout = new javax.swing.GroupLayout(pn_kiri);
        pn_kiri.setLayout(pn_kiriLayout);
        pn_kiriLayout.setHorizontalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(btn_dashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_matakuliah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_dataDosen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_mahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_absen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        pn_kiriLayout.setVerticalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(49, 49, 49)
                .addComponent(btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btn_matakuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btn_dataDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btn_mahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btn_absen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(393, Short.MAX_VALUE))
        );

        getContentPane().add(pn_kiri, java.awt.BorderLayout.LINE_START);

        pn_kanan.setBackground(new java.awt.Color(255, 255, 255));
        pn_kanan.setLayout(new java.awt.BorderLayout());

        pn_navbar.setBackground(new java.awt.Color(0, 206, 201));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Close Window_4.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_navbarLayout = new javax.swing.GroupLayout(pn_navbar);
        pn_navbar.setLayout(pn_navbarLayout);
        pn_navbarLayout.setHorizontalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_navbarLayout.createSequentialGroup()
                .addContainerGap(1365, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        pn_navbarLayout.setVerticalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_navbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pn_kanan.add(pn_navbar, java.awt.BorderLayout.PAGE_START);

        pn_dasar.setBackground(new java.awt.Color(204, 204, 204));

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));
        pn_utama.setLayout(new java.awt.CardLayout());

        pn_mahasiswa.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Today.png"))); // NOI18N
        jLabel5.setText("Data Mahasiswa");

        tblMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NPM", "Nama", "Gender", "Alamat", "Tanggal Lahir", "No HP", "Email"
            }
        ));
        jScrollPane3.setViewportView(tblMahasiswa);

        btn_tampilDataMahasiswa.setBackground(new java.awt.Color(204, 255, 255));
        btn_tampilDataMahasiswa.setText("Tampilkan Data Mahasiswa");
        btn_tampilDataMahasiswa.setBorderPainted(false);
        btn_tampilDataMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tampilDataMahasiswaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_mahasiswaLayout = new javax.swing.GroupLayout(pn_mahasiswa);
        pn_mahasiswa.setLayout(pn_mahasiswaLayout);
        pn_mahasiswaLayout.setHorizontalGroup(
            pn_mahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_mahasiswaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pn_mahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_mahasiswaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(btn_tampilDataMahasiswa)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        pn_mahasiswaLayout.setVerticalGroup(
            pn_mahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_mahasiswaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pn_mahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_tampilDataMahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pn_utama.add(pn_mahasiswa, "card3");

        pn_dosen.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Today.png"))); // NOI18N
        jLabel12.setText("Data Dosen");

        tblDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIDN", "Nama Dosen", "Gender", "No HP", "email", "id matakuliah diajar"
            }
        ));
        jScrollPane4.setViewportView(tblDosen);
        if (tblDosen.getColumnModel().getColumnCount() > 0) {
            tblDosen.getColumnModel().getColumn(4).setHeaderValue("email");
            tblDosen.getColumnModel().getColumn(5).setHeaderValue("id matakuliah diajar");
        }

        btn_tampilDataDosen.setBackground(new java.awt.Color(204, 255, 255));
        btn_tampilDataDosen.setText("Tampilkan Data Dosen");
        btn_tampilDataDosen.setBorderPainted(false);
        btn_tampilDataDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tampilDataDosenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_dosenLayout = new javax.swing.GroupLayout(pn_dosen);
        pn_dosen.setLayout(pn_dosenLayout);
        pn_dosenLayout.setHorizontalGroup(
            pn_dosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dosenLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pn_dosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_dosenLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(btn_tampilDataDosen)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        pn_dosenLayout.setVerticalGroup(
            pn_dosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dosenLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pn_dosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(btn_tampilDataDosen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pn_utama.add(pn_dosen, "card5");

        pn_matakuliah.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Today.png"))); // NOI18N
        jLabel13.setText("Data Matakuliah");

        tblMatakuliah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Matakuliah", "Matakuliah", "SKS", "Hari"
            }
        ));
        jScrollPane5.setViewportView(tblMatakuliah);

        btn_tampilMatakuliah.setBackground(new java.awt.Color(204, 255, 255));
        btn_tampilMatakuliah.setText("Tampilkan Matakuliah");
        btn_tampilMatakuliah.setBorderPainted(false);
        btn_tampilMatakuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tampilMatakuliahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_matakuliahLayout = new javax.swing.GroupLayout(pn_matakuliah);
        pn_matakuliah.setLayout(pn_matakuliahLayout);
        pn_matakuliahLayout.setHorizontalGroup(
            pn_matakuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_matakuliahLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pn_matakuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_matakuliahLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(btn_tampilMatakuliah)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        pn_matakuliahLayout.setVerticalGroup(
            pn_matakuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_matakuliahLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pn_matakuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(btn_tampilMatakuliah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pn_utama.add(pn_matakuliah, "card6");

        pn_absen.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Today.png"))); // NOI18N
        jLabel4.setText("Absen Mahasiswa");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        lb_npm.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lb_npm.setText("ID");

        t_id.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N

        lb_matkul.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lb_matkul.setText("Mata Kuliah");

        lb_keterangan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lb_keterangan.setText("Keterangan");

        comboMK1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboKet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lb_npm)
                .addGap(20, 20, 20)
                .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lb_matkul)
                .addGap(18, 18, 18)
                .addComponent(comboMK1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lb_keterangan)
                .addGap(18, 18, 18)
                .addComponent(comboKet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(376, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_matkul, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboMK1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboKet, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_npm, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel15.setText("Nama");

        t_namaMahasiswa.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel16.setText("Email");

        t_email.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel17.setText("Telepon");

        t_telepon.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N

        jLabel18.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel18.setText("NPM");

        t_npmMahasiswa.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        t_npmMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_npmMahasiswaActionPerformed(evt);
            }
        });

        tbl_Absen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Matakuliah", "Keterangan", "NPM", "Nama", "Email", "Telepon"
            }
        ));
        jScrollPane2.setViewportView(tbl_Absen);

        btn_npmMahasiswa.setText("...");

        btn_Submit.setText("Submit");
        btn_Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_SubmitMousePressed(evt);
            }
        });
        btn_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_absenLayout = new javax.swing.GroupLayout(pn_absen);
        pn_absen.setLayout(pn_absenLayout);
        pn_absenLayout.setHorizontalGroup(
            pn_absenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_absenLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pn_absenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_absenLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pn_absenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_absenLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(20, 20, 20)
                                .addComponent(t_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_absenLayout.createSequentialGroup()
                                .addGroup(pn_absenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                .addGroup(pn_absenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pn_absenLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(pn_absenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(t_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t_namaMahasiswa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pn_absenLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(t_npmMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_npmMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(btn_Submit, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane2)))
                .addGap(50, 50, 50))
        );
        pn_absenLayout.setVerticalGroup(
            pn_absenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_absenLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(pn_absenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_absenLayout.createSequentialGroup()
                        .addGroup(pn_absenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_npmMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_npmMahasiswa))
                        .addGap(18, 18, 18)
                        .addGroup(pn_absenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_namaMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pn_absenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_email, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pn_absenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pn_utama.add(pn_absen, "card4");

        pn_dashboard.setBackground(new java.awt.Color(255, 255, 255));

        btn_rekap.setBackground(new java.awt.Color(204, 255, 255));
        btn_rekap.setText("Tampilkan Rekap");
        btn_rekap.setBorderPainted(false);
        btn_rekap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rekapActionPerformed(evt);
            }
        });

        card_mahasiswa.setBackground(new java.awt.Color(255, 102, 102));

        lb_mahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_mahasiswa.setText("MAHASISWA");

        lb_jumlahmhs.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lb_jumlahmhs.setText("9999");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Student Male.png"))); // NOI18N

        javax.swing.GroupLayout card_mahasiswaLayout = new javax.swing.GroupLayout(card_mahasiswa);
        card_mahasiswa.setLayout(card_mahasiswaLayout);
        card_mahasiswaLayout.setHorizontalGroup(
            card_mahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_mahasiswaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(card_mahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_mahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_jumlahmhs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(25, 25, 25))
        );
        card_mahasiswaLayout.setVerticalGroup(
            card_mahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_mahasiswaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(card_mahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(card_mahasiswaLayout.createSequentialGroup()
                        .addComponent(lb_mahasiswa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_jumlahmhs)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        card_mahasiswa1.setBackground(new java.awt.Color(255, 102, 102));

        lb_mahasiswa1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_mahasiswa1.setText("DOSEN");

        lb_jumlahDsn.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lb_jumlahDsn.setText("9999");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Training.png"))); // NOI18N

        javax.swing.GroupLayout card_mahasiswa1Layout = new javax.swing.GroupLayout(card_mahasiswa1);
        card_mahasiswa1.setLayout(card_mahasiswa1Layout);
        card_mahasiswa1Layout.setHorizontalGroup(
            card_mahasiswa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_mahasiswa1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(card_mahasiswa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_mahasiswa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_jumlahDsn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(34, 34, 34))
        );
        card_mahasiswa1Layout.setVerticalGroup(
            card_mahasiswa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_mahasiswa1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(card_mahasiswa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(card_mahasiswa1Layout.createSequentialGroup()
                        .addComponent(lb_mahasiswa1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_jumlahDsn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        card_mahasiswa2.setBackground(new java.awt.Color(255, 102, 102));

        lb_mahasiswa2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_mahasiswa2.setText("MATAKULIAH");

        lb_jumlahMk.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lb_jumlahMk.setText("9999");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Literature.png"))); // NOI18N

        javax.swing.GroupLayout card_mahasiswa2Layout = new javax.swing.GroupLayout(card_mahasiswa2);
        card_mahasiswa2.setLayout(card_mahasiswa2Layout);
        card_mahasiswa2Layout.setHorizontalGroup(
            card_mahasiswa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_mahasiswa2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(card_mahasiswa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_mahasiswa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_jumlahMk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(25, 25, 25))
        );
        card_mahasiswa2Layout.setVerticalGroup(
            card_mahasiswa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_mahasiswa2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(card_mahasiswa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(card_mahasiswa2Layout.createSequentialGroup()
                        .addComponent(lb_mahasiswa2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_jumlahMk)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setText("Master Data > Dashboard");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dashboard Layout (1).png"))); // NOI18N

        tbl_rekap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NPM", "Nama", "Keterangan", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane6.setViewportView(tbl_rekap);

        javax.swing.GroupLayout pn_dashboardLayout = new javax.swing.GroupLayout(pn_dashboard);
        pn_dashboard.setLayout(pn_dashboardLayout);
        pn_dashboardLayout.setHorizontalGroup(
            pn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dashboardLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pn_dashboardLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_dashboardLayout.createSequentialGroup()
                                .addComponent(card_mahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(card_mahasiswa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(card_mahasiswa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pn_dashboardLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(711, 711, 711)))
                        .addGap(328, 328, 328))
                    .addGroup(pn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_rekap, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        pn_dashboardLayout.setVerticalGroup(
            pn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dashboardLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(card_mahasiswa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(card_mahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(card_mahasiswa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(btn_rekap, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pn_utama.add(pn_dashboard, "card2");

        javax.swing.GroupLayout pn_dasarLayout = new javax.swing.GroupLayout(pn_dasar);
        pn_dasar.setLayout(pn_dasarLayout);
        pn_dasarLayout.setHorizontalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        pn_dasarLayout.setVerticalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_dasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pn_kanan.add(pn_dasar, java.awt.BorderLayout.CENTER);

        getContentPane().add(pn_kanan, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation (x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        pn_utama.removeAll();
        pn_utama.repaint();
        pn_utama.revalidate();
        
        pn_utama.add(pn_dashboard);
        pn_utama.repaint();
        pn_utama.revalidate();
        
        jumlahMahasiswa();
        jumlahMk();
        jumlahDsn();
        loadData();
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_matakuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_matakuliahActionPerformed
        pn_utama.removeAll();
        pn_utama.repaint();
        pn_utama.revalidate();
        
        pn_utama.add(pn_matakuliah);
        pn_utama.repaint();
        pn_utama.revalidate();
        
    }//GEN-LAST:event_btn_matakuliahActionPerformed

    private void btn_dataDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dataDosenActionPerformed
        pn_utama.removeAll();
        pn_utama.repaint();
        pn_utama.revalidate();
        
        pn_utama.add(pn_dosen);
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_dataDosenActionPerformed

    private void btn_mahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mahasiswaActionPerformed
        
        pn_utama.removeAll();
        pn_utama.repaint();
        pn_utama.revalidate();
        
        pn_utama.add(pn_mahasiswa);
        pn_utama.repaint();
        pn_utama.revalidate();
        
    }//GEN-LAST:event_btn_mahasiswaActionPerformed

    private void btn_absenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_absenActionPerformed
        pn_utama.removeAll();
        pn_utama.repaint();
        pn_utama.revalidate();
        
        pn_utama.add(pn_absen);
        pn_utama.repaint();
        pn_utama.revalidate();
        
        isiCombo();
        tampilData();
    }//GEN-LAST:event_btn_absenActionPerformed

    private void t_npmMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_npmMahasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_npmMahasiswaActionPerformed

    private void btn_tampilDataMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tampilDataMahasiswaActionPerformed
        String sql = "SELECT * FROM mahasiswa";
        try{
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblMahasiswa.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String []{rs.getString (1), rs.getString (2), rs.getString (3), rs.getString (4), rs.getString (5), rs.getString (6), rs.getString(7) });
            }
        }catch (Exception ex){
            System.out.println("Error :" +ex.getMessage());
        }
    }//GEN-LAST:event_btn_tampilDataMahasiswaActionPerformed

    private void btn_tampilDataDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tampilDataDosenActionPerformed
        String sql = "SELECT * FROM dosen";
        try{
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblDosen.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String []{rs.getString (1), rs.getString (2), rs.getString (3), rs.getString (4), rs.getString (5), rs.getString (6) });
            }
        }catch (Exception ex){
            System.out.println("Error :" +ex.getMessage());
        }
    }//GEN-LAST:event_btn_tampilDataDosenActionPerformed

    private void btn_tampilMatakuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tampilMatakuliahActionPerformed
        String sql = "SELECT * FROM matakuliah";
        try{
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblMatakuliah.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String []{rs.getString (1), rs.getString (2), rs.getString (3), rs.getString (4) });
            }
        }catch (Exception ex){
            System.out.println("Error :" +ex.getMessage());
        }
    }//GEN-LAST:event_btn_tampilMatakuliahActionPerformed

    private void btn_SubmitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SubmitMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SubmitMousePressed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void btn_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SubmitActionPerformed
        try {
            st = conn.createStatement();
            String sql = "insert into absen values ('"+t_id.getText()+"','"+comboMK1.getSelectedItem()+"','"+comboKet.getSelectedItem()+"','"+t_npmMahasiswa.getText()+"','"+t_namaMahasiswa.getText()+"','"+t_email.getText()+"','"+t_telepon.getText()+"')";
            st.executeUpdate(sql);
            tampilData();
            JOptionPane.showMessageDialog(null, "Berhasil absen");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Absen" +e);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_SubmitActionPerformed

    private void btn_rekapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rekapActionPerformed
        String sql = "SELECT * FROM absen";
        try{
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tbl_rekap.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String []{rs.getString (1), rs.getString (2), rs.getString (3), rs.getString (4),rs.getString (5),rs.getString (6), rs.getString (7) });
            }
        }catch (Exception ex){
            System.out.println("Error :" +ex.getMessage());
        }
    }//GEN-LAST:event_btn_rekapActionPerformed
    
    private void isiCombo(){
        comboMK1.removeAllItems();
        comboMK1.addItem("=Pilih Matakuliah=");
        comboMK1.addItem("PBO");
        comboMK1.addItem("Basis Data");
        comboMK1.addItem("Jaringan Komputer");
        comboMK1.addItem("Keamanan Sistem");
        comboMK1.addItem("Metode Numerik");
        comboMK1.addItem("Bahasa Automata");
        comboMK1.addItem("ADBO");
        
        comboKet.removeAllItems();
        comboKet.addItem("Hadir");
        comboKet.addItem("Izin");
        comboKet.addItem("Sakit");
        comboKet.addItem("Alpa");
        
    }
        private void tampilData(){
            try {
                st = conn.createStatement();
                String sql = "SELECT * FROM absen";
                ResultSet rs  = st.executeQuery(sql);
                DefaultTableModel model = (DefaultTableModel) tbl_Absen.getModel();
                model.setRowCount(0);
                while (rs.next()){
                    model.addRow(new Object []{rs.getString (1), rs.getString (2), rs.getString (3), rs.getString (4), rs.getString (5), rs.getString (6), rs.getString (7) });
                tbl_Absen.setModel(model);
                 
                }    
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "ada kesalahan" +e);
            }
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }
    
    private int jumlahMahasiswa(){
        int totalMahasiswa = 0;
    
        String sql = "SELECT COUNT(*) AS total FROM mahasiswa";
        
        try{
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                totalMahasiswa = rs.getInt ("total");
            }
        }catch (Exception e){
            e.printStackTrace();
        }
        return totalMahasiswa;
    }
    
    private int jumlahMk(){
        int totalMahasiswa = 0;
    
        String sql = "SELECT COUNT(*) AS total FROM matakuliah";
        
        try{
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                totalMahasiswa = rs.getInt ("total");
            }
        }catch (Exception e){
            e.printStackTrace();
        }
        return totalMahasiswa;
    }
    
     private int jumlahDsn(){
        int totalMahasiswa = 0;
    
        String sql = "SELECT COUNT(*) AS total FROM dosen";
        
        try{
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                totalMahasiswa = rs.getInt ("total");
            }
        }catch (Exception e){
            e.printStackTrace();
        }
        return totalMahasiswa;
    }
    
    private void loadData(){
        lb_jumlahmhs.setText(String.valueOf(jumlahMahasiswa()));
        lb_jumlahMk.setText(String.valueOf(jumlahMk()));
        lb_jumlahDsn.setText(String.valueOf(jumlahDsn()));
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Submit;
    private javax.swing.JButton btn_absen;
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JButton btn_dataDosen;
    private javax.swing.JButton btn_mahasiswa;
    private javax.swing.JButton btn_matakuliah;
    private javax.swing.JButton btn_npmMahasiswa;
    private javax.swing.JButton btn_rekap;
    private javax.swing.JButton btn_tampilDataDosen;
    private javax.swing.JButton btn_tampilDataMahasiswa;
    private javax.swing.JButton btn_tampilMatakuliah;
    private javax.swing.JPanel card_mahasiswa;
    private javax.swing.JPanel card_mahasiswa1;
    private javax.swing.JPanel card_mahasiswa2;
    private javax.swing.JComboBox<String> comboKet;
    private javax.swing.JComboBox<String> comboMK1;
    private com.raven.datechooser.DateChooser dateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lb_jumlahDsn;
    private javax.swing.JLabel lb_jumlahMk;
    private javax.swing.JLabel lb_jumlahmhs;
    private javax.swing.JLabel lb_keterangan;
    private javax.swing.JLabel lb_mahasiswa;
    private javax.swing.JLabel lb_mahasiswa1;
    private javax.swing.JLabel lb_mahasiswa2;
    private javax.swing.JLabel lb_matkul;
    private javax.swing.JLabel lb_npm;
    private javax.swing.JPanel pn_absen;
    private javax.swing.JPanel pn_dasar;
    private javax.swing.JPanel pn_dashboard;
    private javax.swing.JPanel pn_dosen;
    private javax.swing.JPanel pn_kanan;
    private javax.swing.JPanel pn_kiri;
    private javax.swing.JPanel pn_mahasiswa;
    private javax.swing.JPanel pn_matakuliah;
    private javax.swing.JPanel pn_navbar;
    private javax.swing.JPanel pn_utama;
    private javax.swing.JTextField t_email;
    private javax.swing.JTextField t_id;
    private javax.swing.JTextField t_namaMahasiswa;
    private javax.swing.JTextField t_npmMahasiswa;
    private javax.swing.JTextField t_telepon;
    private dynamic_subjtable.TableCellEditor tableCellEditor1;
    private dynamic_subjtable.TableCustom tblDosen;
    private dynamic_subjtable.TableCustom tblMahasiswa;
    private dynamic_subjtable.TableCustom tblMatakuliah;
    private dynamic_subjtable.TableCustom tbl_Absen;
    private dynamic_subjtable.TableCustom tbl_rekap;
    // End of variables declaration//GEN-END:variables
}